# Generated by Django 4.1.5 on 2023-02-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='update',
            new_name='updated',
        ),
    ]
