# Generated by Django 4.1.5 on 2023-02-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesBackend', '0002_rename_update_notes_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
