# Generated by Django 4.1.5 on 2023-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesBackend', '0003_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
