# Generated by Django 4.1.5 on 2023-02-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesBackend', '0004_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Title',
            new_name='title',
        ),
    ]
